"""empty message

Revision ID: cf7d8eb7b36e
Revises: e745a3e8ded0
Create Date: 2023-01-23 05:05:58.260559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf7d8eb7b36e'
down_revision = 'e745a3e8ded0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.Integer(), nullable=True))
        batch_op.drop_constraint('consultations_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['faculty'], ['id'])
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('consultations_ibfk_1', 'accounts', ['account_id'], ['id'])
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###
